run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - errcheck
      source: "defer .*\\.Close\\(\\)"
    - linters:
        - errcheck
      source: "defer os\\.Remove"
    - linters:
        - errcheck
      source: "os\\.RemoveAll"
