import { LogEntry, MemoryEntry, RunEvent, SettingsResponse } from "../shared/contracts";

export const testSettings: SettingsResponse = {
  app_name: "Local Agent",
  mode: "standard",
  model: { provider_id: "openai", model_id: "gpt-5.4", display_name: "GPT-5.4" },
  available_models: [{ provider_id: "openai", model_id: "gpt-5.4", display_name: "GPT-5.4", enabled: true, available: true }],
  providers: [{ provider_id: "openai", display_name: "OpenAI", base_url: "http://127.0.0.1", chat_completions_path: "/chat", models_path: "/models" }],
  workspace: { workspace_id: "default", name: "默认工作区", root_path: "D:/newwork/本地智能体", is_active: true },
  available_workspaces: [{ workspace_id: "default", name: "默认工作区", root_path: "D:/newwork/本地智能体", is_active: true }],
  approved_directories: [],
  directory_prompt_enabled: true,
  show_risk_level: true,
  ports: { gateway: 8897, runtime: 8898 },
  runtime_status: { ok: true, name: "runtime", version: "0.1.0" },
  memory_policy: {
    enabled: true,
    recall_strategy: "按需召回",
    write_strategy: "关键结果写入",
    cleanup_strategy: "定期整理",
    storage_root: "D:/newwork/本地智能体/data",
    sqlite_path: "D:/newwork/本地智能体/data/memory.db",
    working_memory_dir: "D:/newwork/本地智能体/data/working",
    long_term_memory_path: "D:/newwork/本地智能体/data/long-term.jsonl",
    knowledge_base_path: "D:/newwork/本地智能体/data/knowledge.jsonl",
    long_term_memory_count: 1,
    knowledge_count: 1,
    working_memory_files: 1,
  },
  diagnostics: {
    repo_root: "D:/newwork/本地智能体",
    storage_root: "D:/newwork/本地智能体/data",
    settings_path: "D:/newwork/本地智能体/settings.json",
    run_log_path: "D:/newwork/本地智能体/logs/run.log",
    event_log_path: "D:/newwork/本地智能体/logs/events.log",
    runtime_reachable: true,
    runtime_version: "0.1.0",
    provider_count: 1,
    model_count: 1,
    workspace_count: 1,
    approved_directory_count: 0,
    siyuan_root: "",
    siyuan_export_dir: "",
    siyuan_auto_write_enabled: false,
    siyuan_sync_enabled: false,
    warnings: [],
    errors: [],
  },
  external_connections: [],
  embedding: { provider_id: "", model_name: "" },
};

export const testMemory: MemoryEntry = {
  id: "memory-1",
  kind: "preference",
  memory_kind: "user_preference",
  title: "保持中文输出",
  summary: "默认中文回复",
  content: "默认用中文输出",
  reason: "项目规则要求",
  scope: "workspace",
  workspace_id: "default",
  session_id: "session-1",
  source_run_id: "run-1",
  source: "runtime",
  source_type: "memory",
  source_title: "规则同步",
  source_event_type: "memory_written",
  source_artifact_path: "D:/newwork/本地智能体/docs/evidence.txt",
  governance_version: "v1",
  governance_reason: "人工确认",
  governance_source: "review",
  governance_at: "2026-04-22T10:00:00Z",
  governance_status: "verified",
  memory_action: "write",
  archive_reason: "",
  verified: true,
  priority: 90,
  archived: false,
  archived_at: "",
  created_at: "2026-04-22T09:00:00Z",
  updated_at: "2026-04-22T10:00:00Z",
  timestamp: "2026-04-22T10:00:00Z",
};

export const testRunEvent: RunEvent = {
  event_id: "event-1",
  event_type: "run_finished",
  session_id: "session-1",
  run_id: "run-1",
  sequence: 1,
  timestamp: "2026-04-22T10:00:00Z",
  stage: "verify",
  summary: "完成最小验证",
  detail: "页面结构与状态均已验证",
  result_summary: "验证完成",
  completion_status: "completed",
  tool_display_name: "verify",
  tool_category: "validation",
  risk_level: "low",
  metadata: {
    next_step: "继续补更多工作台测试",
    task_title: "核对工作台状态",
  },
};

export const testSidebarToolEvent: RunEvent = {
  event_id: "event-tool-1",
  event_type: "action_completed",
  session_id: "session-1",
  run_id: "run-1",
  sequence: 2,
  timestamp: "2026-04-22T10:01:00Z",
  stage: "plan",
  summary: "已分析当前工作区",
  detail: "最近动作已收口",
  result_summary: "最近动作已收口",
  tool_name: "read_workspace",
  tool_display_name: "read_workspace",
  tool_category: "read",
  activity_state: "completed",
  artifact_path: "D:/newwork/本地智能体/docs/plan.md",
  context_snapshot: {
    session_summary: "已进入任务分析阶段",
    memory_digest: "已有工作台结构结论",
    knowledge_digest: "Logs / Review 已合并",
    reasoning_summary: "优先补结构测试",
  },
  verification_snapshot: { passed: true, summary: "当前动作验证通过" },
  metadata: {
    next_step: "继续补侧栏与底部面板测试",
    task_title: "核对任务状态",
  },
};

export const testSidebarMemoryEvent: RunEvent = {
  event_id: "event-memory-1",
  event_type: "memory_written",
  session_id: "session-1",
  run_id: "run-1",
  sequence: 3,
  timestamp: "2026-04-22T10:02:00Z",
  stage: "memory",
  summary: "已写入工作区记忆",
  detail: "记录工作台结构约束",
  source_type: "memory",
  verification_snapshot: { passed: true, summary: "记忆写入已验证" },
  metadata: {
    governance_status: "verified",
    memory_kind: "user_preference",
    memory_action: "write",
    next_step: "继续查看侧栏风险与状态沉淀",
    task_title: "核对任务状态",
  },
};

export const testLogEntry: LogEntry = {
  log_id: "log-1",
  session_id: "session-1",
  run_id: "run-1",
  timestamp: "2026-04-22T10:00:00Z",
  level: "info",
  category: "result",
  source: "runtime",
  event_type: "run_finished",
  stage: "review",
  summary: "已完成工作台复盘",
  detail: "Logs 与 Review 结构已经对齐",
  result_summary: "工作台结构稳定",
  final_answer: "History / Review 挂在 Logs 工作区内。",
  completion_status: "completed",
  verification_summary: "已核对结构归属",
  verification_snapshot: { passed: true, summary: "结构归属验证通过" },
  context_snapshot: {
    workspace_root: "D:/newwork/本地智能体",
    memory_digest: "已记录结构事实",
    knowledge_digest: "Review 与 Logs 同视图",
    reasoning_summary: "优先验证页面归属",
    cache_status: "hit",
    cache_reason: "recent",
  },
  metadata: {
    task_title: "核对 Logs / Review 结构",
    next_step: "继续补更多结构测试",
  },
};
